[[main]]
name = "Minecraft"
pageRef = "minecraft"
identifier = "IdzeaCNytg"
weight = 80

[[main]]
name = "Worlds"
pageRef = "worlds"
identifier = "QgtMKFt7Qt"
weight = 90

[[main]]
name = "Useful Resources"
pageRef= "resources"
weight = 100

[[footer]]
none = "none"
