baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Project'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.link]
        useEmbedded = 'auto'